export default  {
  Europe: [
{id:"001",code:	"AL", name:	"Albania"},
{id:"002",code:	"AD", name:	"Andorra"},
{id:"003",code:	"AT", name:	"Austria"},
{id:"004",code:	"BY", name:	"Belarus"},
{id:"005",code:	"BE", name:	"Belgium"},
{id:"006",code:	"BA", name:	"Bosnia and Herzegovina"},
{id:"007",code:	"BG", name:	"Bulgaria"},
{id:"008",code:	"HY", name:	"Croatia"},
{id:"044",code:	"CY", name:	"Cyprus"},
{id:"009",code:	"CZ", name:	"Czechia"},
{id:"010",code:	"DK", name:	"Denmark"},
{id:"011",code:	"EE", name:	"Estonia"},
{id:"012",code:	"FI", name:	"Finland"},
{id:"013",code:	"FR", name:	"France"},
{id:"014",code:	"DE", name:	"Germany"},
{id:"015",code:	"GR", name:	"Greece"},
{id:"016",code:	"HU", name:	"Hungary"},
{id:"017",code:	"IS", name:	"Iceland"},
{id:"018",code:	"IE", name:	"Ireland"},
{id:"019",code:	"IT", name:	"Italy"},
{id:"047",code:	"KO", name:	"Kosovo"},
{id:"020",code:	"LV", name:	"Latvia"},
{id:"021",code:	"LI", name:	"Liechtenstein"},
{id:"022",code:	"LT", name:	"Lithuania"},
{id:"023",code:	"LU", name:	"Luxembourg"},
{id:"024",code:	"MK", name:	"North Macedonia"},
{id:"025",code:	"MT", name:	"Malta"},
{id:"026",code:	"MD", name:	"Moldova"},
{id:"027",code:	"MC", name:	"Monaco"},
{id:"028",code:	"MO", name:	"Montenegro"},
{id:"029",code:	"NL", name:	"Netherlands"},
{id:"030",code:	"NO", name:	"Norway"},
{id:"031",code:	"PL", name:	"Poland"},
{id:"032",code:	"PT", name:	"Portugal"},
{id:"033",code:	"RO", name:	"Romania"},
{id:"046",code:	"RU", name:	"Russia"},
{id:"034",code:	"SM", name:	"San Marino"},
{id:"035",code:	"CS", name:	"Serbia"},
{id:"036",code:	"SK", name:	"Slovakia"},
{id:"037",code:	"SL", name:	"Slovenia"},
{id:"038",code:	"ES", name:	"Spain"},
{id:"039",code:	"SE", name:	"Sweden"},
{id:"040",code:	"CH", name:	"Switzerland"},
{id:"045",code:	"TK", name:	"Turkey"},
{id:"041",code:	"UA", name:	"Ukraine"},
{id:"042",code:	"UK", name:	"UK"},
{id:"043",code:	"VA", name:	"Vatican City"},
  ],
  Asia: [
{id:"001", code:	"AF",name:	"Afghanistan"},
{id:"002", code:	"AM",name:	"Armenia"},
{id:"003", code:	"AZ",name:	"Azerbaijan"},
{id:"060", code:	"BA",name:	"Bahrain"},
{id:"005", code:	"BD",name:	"Bangladesh"},
{id:"006", code:	"BT",name:	"Bhutan"},
{id:"007", code:	"BN",name:	"Brunei"},
{id:"008", code:	"MM",name:	"Myanmar"},
{id:"009", code:	"KH",name:	"Cambodia"},
{id:"010", code:	"CN",name:	"China"},
{id:"012", code:	"TP",name:	"Timor-Leste"},
{id:"013", code:	"GE",name:	"Georgia"},
{id:"050", code:	"HK",name:	"Hong Kong"},
{id:"014", code:	"IN",name:	"India"},
{id:"015", code:	"ID",name:	"Indonesia"},
{id:"016", code:	"IR",name:	"Iran"},
{id:"054", code:	"IZ",name:	"Iraq"},
{id:"063", code:	"IS",name:	"Israel"},
{id:"019", code:	"JP",name:	"Japan"},
{id:"062", code:	"JO",name:	"Jordan"},
{id:"021", code:	"KZ",name:	"Kazakhstan"},
{id:"022", code:	"KP",name:	"Korea, (north)"},
{id:"023", code:	"KR",name:	"S. Korea"},
{id:"061", code:	"KU",name:	"Kuwait"},
{id:"025", code:	"KG",name:	"Kyrgyzstan"},
{id:"026", code:	"LA",name:	"Laos"},
{id:"064", code:	"LE",name:	"Lebanon"},
{id:"051", code:	"MO",name:	"Macau"},
{id:"028", code:	"MY",name:	"Malaysia"},
{id:"030", code:	"MN",name:	"Mongolia"},
{id:"031", code:	"NP",name:	"Nepal"},
{id:"057", code:	"MU",name:	"Oman"},
{id:"033", code:	"PK",name:	"Pakistan"},
{id:"034", code:	"PH",name:	"Philippines"},
{id:"059", code:	"QA",name:	"Qatar"},
{id:"036", code:	"RU",name:	"Russia"},
{id:"055", code:	"SA",name:	"Saudi Arabia"},
{id:"038", code:	"SG",name:	"Singapore"},
{id:"039", code:	"LK",name:	"Sri Lanka"},
{id:"053", code:	"SY",name:	"Syria"},
{id:"049", code:	"TW",name:	"Taiwan"},
{id:"041", code:	"TJ",name:	"Tajikistan"},
{id:"042", code:	"TH",name:	"Thailand"},
{id:"052", code:	"TU",name:	"Turkey"},
{id:"044", code:	"TM",name:	"Turkmenistan"},
{id:"058", code:	"AE",name:	"United Arab Emirates"},
{id:"046", code:	"UZ",name:	"Uzbekistan"},
{id:"047", code:	"VN",name:	"Vietnam"},
{id:"056", code:	"YM",name:	"Yemen"},
  ],
  // Oceania: [
  //   'American Samoa',
  //   'Australia',
  //   'Christmas Island',
  //   'Cocos (Keeling) Islands',
  //   'Cook Islands',
  //   'Fiji Islands',
  //   'French Polynesia',
  //   'Guam',
  //   'Kiribati',
  //   'Marshall Islands',
  //   'Micronesia, Federated States of',
  //   'Nauru',
  //   'New Caledonia',
  //   'New Zealand',
  //   'Niue',
  //   'Norfolk Island',
  //   'Northern Mariana Islands',
  //   'Palau',
  //   'Papua New Guinea',
  //   'Pitcairn',
  //   'Samoa',
  //   'Solomon Islands',
  //   'Tokelau',
  //   'Tonga',
  //   'Tuvalu',
  //   'United States Minor Outlying Islands',
  //   'Vanuatu',
  //   'Wallis and Futuna'
  // ],
  Africa: [
{id:"001", code:"	DZ",name:"Algeria"},
{id:"002", code:"	AO",name:"Angola"},
{id:"003", code:"	BJ",name:"Benin"},
{id:"004", code:"	BW",name:"Botswana"},
{id:"005", code:"	BF",name:"Burkina Faso"},
{id:"006", code:"	BI",name:"Burundi"},
{id:"007", code:"	CM",name:"Cameroon"},
{id:"059", code:"	CA",name:"Canary Islands"},
{id:"008", code:"	CV",name:"Cape Verde"},
{id:"009", code:"	CR",name:"Central African Republic"},
{id:"010", code:"	TD",name:"Chad"},
{id:"057", code:"	CG",name:"Congo"},
{id:"012", code:"	CI",name:"Cote d'Ivoire"},
{id:"013", code:"	CD",name:"Democratic Republic of the Congo"},
{id:"014", code:"	DJ",name:"Djibouti"},
{id:"015", code:"	EG",name:"Egypt"},
{id:"016", code:"	GQ",name:"Equatorial Guinea"}, 
{id:"017", code:"	ER",name:"Eritrea"},
{id:"018", code:"	ET",name:"Ethiopia"},
{id:"019", code:"	GA",name:"Gabon"},
{id:"056", code:"	GM",name:"Gambia"},
{id:"020", code:"	GH",name:"Ghana"},
{id:"021", code:"	GN",name:"Guinea"},
{id:"022", code:"	GW",name:"Guinea-Bissau"},
{id:"023", code:"	KE",name:"Kenya"},
{id:"024", code:"	LS",name:"Lesotho"},
{id:"025", code:"	LI",name:"Liberia"},
{id:"026", code:"	LR",name:"Libya"},
{id:"027", code:"	MG",name:"Madagascar"},
{id:"028", code:"	MW",name:"Malawi"},
{id:"029", code:"	ML",name:"Mali"},
{id:"030", code:"	MR",name:"Mauritania"},
{id:"058", code:"	MU",name:"Mauritius"},
{id:"032", code:"	MA",name:"Morocco"},
{id:"033", code:"	MZ",name:"Mozambique"},
{id:"034", code:"	NA",name:"Namibia"},
{id:"035", code:"	NE",name:"Niger"},
{id:"036", code:"	NG",name:"Nigeria"},
{id:"038", code:"	RW",name:"Rwanda"},
{id:"040", code:"	ST",name:"Sao Tome and Principe"},
{id:"041", code:"	SN",name:"Senegal"},
{id:"042", code:"	SY",name:"Seychelles"},
{id:"043", code:"	SL",name:"Sierra Leone"},
{id:"044", code:"	SO",name:"Somalia"},
{id:"045", code:"	ZA",name:"South Africa"},
{id:"060", code:"	SS",name:"South Sudan"},
{id:"046", code:"	SD",name:"Sudan"},
{id:"047", code:"	SZ",name:"Swaziland"},
{id:"048", code:"	TZ",name:"Tanzania"},
{id:"049", code:"	TG",name:"Togo"},
{id:"051", code:"	TN",name:"Tunisia"},
{id:"052", code:"	UG",name:"Uganda"},
{id:"011", code:"	KM",name:"Union of Comoros"},
{id:"053", code:"	WS",name:"Western Sahara"},
{id:"054", code:"	ZM",name:"Zambia"},
{id:"055", code:"	ZW",name:"Zimbabwe"},
  ],
  'North America': [
   { id:"001", code:	"AG", name:"Antigua and Barbuda"},
   { id:"002", code:	"BS", name:"Bahamas"},
   { id:"003", code:	"BB", name:"Barbados"},
   { id:"004", code:	"BZ", name:"Belize"},
   { id:"005", code:	"CA", name:"Canada"},
   { id:"026", code:	"KY", name:"Cayman Islands"},
   { id:"006", code:	"CR", name:"Costa Rica"},
   { id:"007", code:	"CU", name:"Cuba"},
   { id:"008", code:	"DM", name:"Dominica"},
   { id:"009", code:	"DO", name:"Dominican Republic"},
   { id:"010", code:	"SV", name:"El Salvador"},
   { id:"024", code:	"GL", name:"Greenland"},
   { id:"011", code:	"GD", name:"Grenada"},
   { id:"012", code:	"GT", name:"Guatemala"},
   { id:"013", code:	"HT", name:"Haiti"},
   { id:"014", code:	"HN", name:"Honduras"},
   { id:"015", code:	"JM", name:"Jamaica"},
   { id:"016", code:	"MX", name:"Mexico"},
   { id:"017", code:	"NI", name:"Nicaragua"},
   { id:"018", code:	"PA", name:"Panama"},
   { id:"025", code:	"PR", name:"Puerto Rico"},
   { id:"019", code:	"KN", name:"St. Kitts & Nevis"},
   { id:"020", code:	"LC", name:"St. Lucia"},
   { id:"021", code:	"VC", name:"St. Vincent & the Grenadines"},
   { id:"022", code:	"TT", name:"Trinidad & Tobago"},
   { id:"023", code:	"US", name:"USA"},
  ],
  'South America': [
{id:"001",code:	"AR",name:	"Argentina"},
{id:"002",code:	"BO",name:	"Bolivia"},
{id:"003",code:	"BR",name:	"Brazil"},
{id:"004",code:	"CL",name:	"Chile"},
{id:"005",code:	"CO",name:	"Colombia"},
{id:"006",code:	"EC",name:	"Ecuador"},
{id:"007",code:	"FK",name:	"Falkland Islands"},
{id:"008",code:	"GF",name:	"French Guiana"},
{id:"015",code:	"GI",name:	"Galapagos Islands"},
{id:"009",code:	"GY",name:	"Guyana"},
{id:"010",code:	"PY",name:	"Paraguay"},
{id:"011",code:	"PE",name:	"Peru"},
{id:"016",code:	"SG",name:	"South Georgia Island"},
{id:"012",code:	"SR",name:	"Suriname"},
{id:"013",code:	"UY",name:	"Uruguay"},
{id:"014",code:	"VE",name:	"Venezuela"},
  ],
  // Antarctica: [
  //   'Antarctica',
  //   'Bouvet Island',
  //   'French Southern territories',
  //   'Heard Island and McDonald Islands',
  //   'South Georgia and the South Sandwich Islands'
  // ]
}
